/**************************/
/* Get API Token
/**************************/
export const GET_CLIENT_SERVICES_REQUEST = 'GET_CLIENT_SERVICES_REQUEST';
export const GET_CLIENT_SERVICES_SUCCESS = 'GET_CLIENT_SERVICES_SUCCESS';
export const GET_CLIENT_SERVICES_FAILED = 'GET_CLIENT_SERVICES_FAILED';

export const INITIAL_STORE = 'INITIAL_STORE';